prometheus:
  prometheusSpec:
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 500Mi
    externalLabels:
      cluster: mycluster6
      region: southamerica-east1-a
