prometheus:
  prometheusSpec:
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 500Mi
    externalLabels:
      cluster: mycluster3
      region: sa-east-1
